In [1]:
import numpy as np

#### __1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

In [5]:
# а)

A = np.random.randint(0, 9, (4, 2))
B = np.random.randint(0, 9, (4, 2))

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

try:
    np.dot(A, B)
    print('Произведение матриц A x B определено.\n')
    print(f'Размерность произведения A x B : {(np.dot(A, B)).shape}\n')
except Exception:
    print('Произведение матриц A x B не определено.\n')
    
    
try:
    np.dot(B, A)
    print('Произведение матриц B x A определено.\n')
    print(f'Размерность произведения B x A: {(np.dot(B, A)).shape}\n')
except Exception:
    print('Произведение матриц B x A не определено.\n')        

A:
[[4 4]
 [2 0]
 [4 6]
 [7 6]]

B:
[[4 7]
 [1 5]
 [6 5]
 [3 5]]

Произведение матриц A x B не определено.

Произведение матриц B x A не определено.



In [8]:
# б)

A = np.random.randint(0, 9, (2, 5))
B = np.random.randint(0, 9, (5, 3))

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

try:
    np.dot(A, B)
    print('Произведение матриц A x B определено.\n')
    print(f'Размерность произведения A x B : {(np.dot(A, B)).shape}\n')    
except Exception:
    print('Произведение матриц A x B не определено.\n')
    
    
try:
    np.dot(B, A)
    print('Произведение матриц B x A определено.\n')
    print(f'Размерность произведения B x A: {(np.dot(B, A)).shape}\n')
except Exception:
    print('Произведение матриц B x A не определено.\n') 
    

A:
[[5 2 4 3 6]
 [0 0 3 4 1]]

B:
[[8 2 0]
 [3 1 0]
 [1 2 4]
 [3 0 3]
 [2 8 6]]

Произведение матриц A x B определено.

Размерность произведения A x B : (2, 3)

Произведение матриц B x A не определено.



In [9]:
# в)

A = np.random.randint(0, 9, (8, 3))
B = np.random.randint(0, 9, (3, 8))

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

try:
    np.dot(A, B)
    print('Произведение матриц A x B определено.\n')
    print(f'Размерность произведения A x B : {(np.dot(A, B)).shape}\n')    
except Exception:
    print('Произведение матриц A x B не определено.\n')
    
    
try:
    np.dot(B, A)
    print('Произведение матриц B x A определено.\n')
    print(f'Размерность произведения B x A: {(np.dot(B, A)).shape}\n')
except Exception:
    print('Произведение матриц B x A не определено.\n') 
    

A:
[[0 1 5]
 [1 0 6]
 [4 1 7]
 [6 5 1]
 [4 4 7]
 [2 3 8]
 [4 1 6]
 [5 7 4]]

B:
[[5 8 7 4 5 1 2 3]
 [8 0 1 4 7 3 7 0]
 [7 4 5 0 5 4 7 4]]

Произведение матриц A x B определено.

Размерность произведения A x B : (8, 8)

Произведение матриц B x A определено.

Размерность произведения B x A: (3, 3)



In [10]:
# г)

A = np.random.randint(0, 9, (4, 4))
B = np.random.randint(0, 9, (4, 4))

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

try:
    np.dot(A, B)
    print('Произведение матриц A x B определено.\n')
    print(f'Размерность произведения A x B : {(np.dot(A, B)).shape}\n')    
except Exception:
    print('Произведение матриц A x B не определено.\n')
    
    
try:
    np.dot(B, A)
    print('Произведение матриц B x A определено.\n')
    print(f'Размерность произведения B x A: {(np.dot(B, A)).shape}\n')
except Exception:
    print('Произведение матриц B x A не определено.\n') 
    

A:
[[6 5 2 8]
 [1 4 3 5]
 [7 1 4 8]
 [5 1 2 4]]

B:
[[4 6 2 3]
 [1 1 3 2]
 [7 3 3 3]
 [6 2 2 4]]

Произведение матриц A x B определено.

Размерность произведения A x B : (4, 4)

Произведение матриц B x A определено.

Размерность произведения B x A: (4, 4)



#### __2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [12]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'A + B:\n{A + B}\n')
print(f'A x B:\n{np.dot(A, B)}\n')
print(f'B x A:\n{np.dot(B, A)}\n')


A + B:
[[ 5 -3]
 [ 3  5]]

A x B:
[[  4 -11]
 [ 12  -3]]

B x A:
[[ 1 -8]
 [15  0]]



#### __3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [13]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

print(f'3A - 2B + 4C:\n{3 * A - 2 * B + 4 * C}\n')


3A - 2B + 4C:
[[ 11  -5]
 [  9 -12]]



#### __4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [14]:
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'A x A.T:\n{np.dot(A, A.T)}\n')
print(f'A.T x A:\n{np.dot(A.T, A)}\n')


A x A.T:
[[17 18 11]
 [18 29  4]
 [11  4 13]]

A.T x A:
[[45  0]
 [ 0 14]]

