In [2]:
import numpy as np
import math
import copy

#### __1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [3]:
# а)

x = math.pi / 4

A = np.array([[math.sin(x), -math.cos(x)], [math.cos(x), math.sin(x)]])

det_A = A[0][0] * A[1][1] - A[0][1] * A[1][0]

print(f'det(A): {det_A}\n')

print(f'NumPy det(A): {np.linalg.det(A)}\n')

det(A): 1.0000000000000002

NumPy det(A): 1.0



In [4]:
# б)

A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])

det_A = (
    A[0][0] * A[1][1] * A[2][2] +
    A[0][1] * A[1][2] * A[2][0] +
    A[0][2] * A[1][0] * A[2][1] -
    A[0][2] * A[1][1] * A[2][0] -
    A[0][1] * A[1][0] * A[2][2] -
    A[0][0] * A[1][2] * A[2][1])

print(f'det(A): {det_A}\n')

print(f'NumPy det(A): {np.linalg.det(A)}\n')

det(A): 180

NumPy det(A): 180.0



In [5]:
# в)

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

det_A = (
    A[0][0] * A[1][1] * A[2][2] +
    A[0][1] * A[1][2] * A[2][0] +
    A[0][2] * A[1][0] * A[2][1] -
    A[0][2] * A[1][1] * A[2][0] -
    A[0][1] * A[1][0] * A[2][2] -
    A[0][0] * A[1][2] * A[2][1])

print(f'det(A): {det_A}\n')

print(f'NumPy det(A): {np.linalg.det(A)}\n')

det(A): 0

NumPy det(A): -9.51619735392994e-16



#### __2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

In [6]:
A = np.array([[1, -2], [1, 2]])

print(f'det(A): {np.linalg.det(A)}\n')

det(A): 4.0



а) $det(A^{2}) = det(A x A) = det(A) * det(A) = 16$<br>

In [7]:
print(f'det(A^2): {np.linalg.det(np.dot(A, A))}\n')

det(A^2): 16.000000000000007



б) $det(A^{T})$ = $det(A)$ = $4$<br>

In [8]:
print(f'det(A.T): {np.linalg.det(A.T)}\n')

det(A.T): 4.0



в) $det(2A)$ = $k^{n}det(A)$ = $2^{n} * 4$ = $2^{n+2}$<br>

In [9]:
print(f'det(2A): {np.linalg.det(2 * A)}\n')

det(2A): 15.999999999999998



#### __3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Если $det(A) = 0$, то матрица A вырождена.<br>

In [12]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'det(A): {np.linalg.det( A)}\n')

det(A): 0.0



#### __4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

__Определение__

_Строчным рангом матрицы_ называется максимальное число линейно независимых строк этой матрицы.

_Столбцовым рангом матрицы_ называется максимальное число линейно независимых столбцов этой матрицы.

__Теорема__

_Строчный ранг матрицы всегда совпадает с столбцовым и равен максимальному размеру ее невырожденного минора._

In [13]:
# а)

A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])

print(f'A:\n{A}\n')

A:
[[1 2 3]
 [1 1 1]
 [2 3 4]]



Третья строка матрицы A является линейной комбинацией (суммой) первой и второй строк матрицы A, поэтому rank(A) - 2

In [13]:
print(f'rank(A): {np.linalg.matrix_rank(A)}\n')

rank(A): 2



In [15]:
# б)

A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])

print(f'A:\n{A}\n')

A:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]



Первая строка матрицы A является линейной комбинацией (разностью) третьей и второй строк матрицы A, поэтому rank(A) - 3

In [16]:
print(f'rank(A): {np.linalg.matrix_rank(A)}\n')

rank(A): 3

